services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:15
    container_name: teleport
    hostname: localhost
    restart: unless-stopped
    ports:
      - "3023:3023"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - teleport_data:/var/lib/teleport
      - ./teleport.yaml:/etc/teleport/teleport.yaml:ro

volumes:
  teleport_data:
