version: "3.8"

services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:14
    container_name: teleport
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_PTRACE
    ports:
      - "3022:3022"   # SSH
      - "3023:3023"   # Proxy SSH
      - "3024:3024"   # Reverse tunnel
      - "3080:3080"   # Web UI
    volumes:
      - teleport-data:/var/lib/teleport
      - ./teleport.yaml:/etc/teleport.yaml

    command: ["start", "--config=/etc/teleport.yaml"]

volumes:
  teleport-data:
